# Generated by Django 5.2.5 on 2025-09-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=5, null=True, unique=True)),
            ],
        ),
    ]
