# Generated by Django 5.2.5 on 2025-09-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomplayer',
            name='player',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
